---
- name: Ensure iptables is present.
  package:
    name: iptables
    state: present

- name: Install flush script
  copy:
    src: iptables-flush.sh
    dest: /etc/firewall-flush.bash
    mode: 0755
    owner: root
    group: root
  notify: restart firewall

- name: Flush iptables the first time playbook runs.
  command: >
      /etc/firewall-flush.bash
  args:
    creates: /etc/firewall.bash

- name: Copy firewall systemd unit file into place (for systemd systems).
  template:
    src: firewall.unit.j2
    dest: /etc/systemd/system/firewall.service
    owner: root
    group: root
    mode: 0644
  notify:
    - systemctl daemon-reload
    - restart firewall

- name: Copy firewall script into place.
  template:
    src: firewall.bash.j2
    dest: /etc/firewall.bash
    owner: root
    group: root
    mode: 0744
  notify: restart firewall

- meta: flush_handlers

- name: Configure the firewall service.
  service:
    name: firewall
    state: "{{ firewall_state }}"
    enabled: "{{ firewall_enabled_at_boot }}"

- import_tasks: disable-other-firewalls.yml
  when: firewall_disable_firewalld or firewall_disable_ufw
