---

- name: restart firewall
  become: true
  service:
    name: firewall
    state: restarted
  tags: firewall

- name: systemctl daemon-reload
  become: true
  systemd:
    daemon_reload: true
  tags: firewall
